### ISSUE TITLE
0.0.8 版本的`saveImageToGallery`代码有问题

### ISSUE THREAD

**Issue by kitsudog** [lucky1213/media_assets_utils#3]
/media_asset_utils/MediaAssetsUtilsPlugin.kt: (322, 21): Unresolved reference: bmp
/media_asset_utils/MediaAssetsUtilsPlugin.kt: (322, 62): Unresolved reference: quality

**Comment by lucky1213** [comment]
感谢，此处存在bug，会进行修复
